services:
#    maic_blog.example:
#        class: Maic\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    maic_blog.slugger:
        class: Maic\BlogBundle\Service\Slugger