maic_client:
    resource: "@MaicClientBundle/Controller/"
    type:     annotation
    prefix:   /

maic_blog:
    resource: "@MaicBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# import routes from a controller directory
blog:
    resource: "@MaicBlogBundle/Controller"
    type:     annotation