<?php

namespace Maic\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository {

    public function getArticles() {
        $queryBuilder = $this->createQueryBuilder('a') // a alias pour article
                ->leftJoin('a.image', 'i') // i alias pour image
                ->addSelect('i')
                ->leftJoin('a.categories', 'c') // c alias pour categories
                ->addSelect('c')
                ->where('a.publication = :val')
                ->setParameter('val', 1)
                ->orderBy('a.datecreation', 'DESC')
        ;
        $result = $queryBuilder->getQuery()->getResult();
        return $result;
    }

    public function getArticleDetails($id) {
        $queryBuilder = $this->createQueryBuilder('a') // a alias pour article
                ->where('a.id = ?1')
                ->setParameter(1, $id)
                
                ->leftJoin('a.image', 'i') // i alias pour image
                ->addSelect('i')
                
                ->leftJoin('a.categories', 'ca') // ca alias pour categories
                ->addSelect('ca')
                
                ->leftJoin('a.commentaires', 'co') // co alias pour categories
                ->addSelect('co')
        ;
        $result = $queryBuilder->getQuery()->getSingleResult();
        return $result;
    }

}
